/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nrproject;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 */
public class UpdatePlayer extends javax.swing.JFrame {
    String path2 = null;
    /**
     * Creates new form UpdatePlayer
     */
    public UpdatePlayer() {
        setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add_club = new javax.swing.JTextField();
        search_name = new javax.swing.JTextField();
        add_country = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        update_player = new javax.swing.JButton();
        add_position = new javax.swing.JTextField();
        add_played = new javax.swing.JTextField();
        add_goals = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        add_assists = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        add_clean_sheets = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        add_back = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        upload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        add_photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 219, 251));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(454, 480));

        add_club.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_club.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_clubActionPerformed(evt);
            }
        });

        search_name.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        search_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_nameActionPerformed(evt);
            }
        });

        add_country.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_countryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setText("Full Name :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setText("Country :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setText("Club :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel7.setText("Position :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel8.setText("Games Played :");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        min.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        min.setText("-");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        update_player.setBackground(new java.awt.Color(0, 0, 0));
        update_player.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        update_player.setForeground(new java.awt.Color(255, 255, 255));
        update_player.setText("UPDATE PLAYER");
        update_player.setAlignmentY(0.0F);
        update_player.setBorderPainted(false);
        update_player.setFocusPainted(false);
        update_player.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        update_player.setMargin(new java.awt.Insets(2, 10, 2, 10));
        update_player.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_playerActionPerformed(evt);
            }
        });

        add_position.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_positionActionPerformed(evt);
            }
        });

        add_played.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_played.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_playedActionPerformed(evt);
            }
        });

        add_goals.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_goalsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setText("Goals :");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_assists.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_assists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_assistsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel10.setText("Assists :");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_clean_sheets.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        add_clean_sheets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_clean_sheetsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel11.setText("Clean Sheets :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_back.setBackground(new java.awt.Color(0, 0, 0));
        add_back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        add_back.setForeground(new java.awt.Color(255, 255, 255));
        add_back.setText("BACK TO ADMIN PANEL");
        add_back.setAlignmentY(0.0F);
        add_back.setBorderPainted(false);
        add_back.setFocusPainted(false);
        add_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_back.setIconTextGap(0);
        add_back.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_backActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.setAlignmentY(0.0F);
        search.setBorderPainted(false);
        search.setFocusPainted(false);
        search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        search.setMargin(new java.awt.Insets(2, 10, 2, 10));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setText("PLAYER DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(94, 94, 94)
                        .addComponent(min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(add_country, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(add_club, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(search)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(add_back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update_player))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add_position, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_played, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_assists, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_clean_sheets, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(min)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_country, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_club, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_position, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_played, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_assists, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_clean_sheets, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_player)
                    .addComponent(add_back))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        upload.setBackground(new java.awt.Color(0, 0, 0));
        upload.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        upload.setForeground(new java.awt.Color(255, 255, 255));
        upload.setText("UPDATE PHOTO");
        upload.setToolTipText("");
        upload.setAlignmentY(0.0F);
        upload.setBorderPainted(false);
        upload.setFocusPainted(false);
        upload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        upload.setIconTextGap(0);
        upload.setMargin(new java.awt.Insets(2, 10, 2, 10));
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("SQUARE PHOTO DIMENSION IS REQUIRED AND 400X400 IS PREFERRED");
        jLabel1.setPreferredSize(new java.awt.Dimension(388, 15));

        add_photo.setAlignmentY(0.0F);
        add_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 2));
        add_photo.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(upload, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upload))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_clubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_clubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_clubActionPerformed

    private void search_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_nameActionPerformed

    private void add_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_countryActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void update_playerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_playerActionPerformed
        // TODO add your handling code here:
        if (search_name.getText().isEmpty() || add_country.getText().isEmpty() || add_club.getText().isEmpty()
            || add_position.getText().isEmpty() || add_played.getText().isEmpty() || add_goals.getText().isEmpty()
            || add_assists.getText().isEmpty() || add_clean_sheets.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the data required");
        } else {
            String name = search_name.getText();
            String country = add_country.getText();
            String club = add_club.getText();
            String position = add_position.getText();
            String played = add_played.getText();
            String goals = add_goals.getText();
            String assists = add_assists.getText();
            String clean_sheets = add_clean_sheets.getText();
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/players", "root", "1234");
                if(path2!=null){
                    String sqlquery = "update playerdata set country=?,club=?,position=?,played=?,goals=?,assists=?,cleansheets=?,pic=? where name = ?";
                    PreparedStatement ps = conn.prepareStatement(sqlquery);
                    ps.setString(9, name);
                    ps.setString(1, country);
                    ps.setString(2, club);
                    ps.setString(3, position);
                    ps.setString(4, played);
                    ps.setString(5, goals);
                    ps.setString(6, assists);
                    ps.setString(7, clean_sheets);
                    InputStream is = new FileInputStream(new File(path2));
                    ps.setBlob(8, is);
                    ps.executeUpdate();
                }
                else{
                    String sqlquery = "update playerdata set country=?,club=?,position=?,played=?,goals=?,assists=?,cleansheets=? where name = ?";
                    PreparedStatement ps = conn.prepareStatement(sqlquery);
                    ps.setString(8, name);
                    ps.setString(1, country);
                    ps.setString(2, club);
                    ps.setString(3, position);
                    ps.setString(4, played);
                    ps.setString(5, goals);
                    ps.setString(6, assists);
                    ps.setString(7, clean_sheets);
                    ps.executeUpdate();
                }
                search_name.setText("");
                add_country.setText("");
                add_club.setText("");
                add_position.setText("");
                add_played.setText("");
                add_goals.setText("");
                add_assists.setText("");
                add_clean_sheets.setText("");
                add_photo.setIcon(null);
                JOptionPane.showMessageDialog(null, "Player Updated Successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_update_playerActionPerformed

    private void add_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_positionActionPerformed

    private void add_playedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_playedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_playedActionPerformed

    private void add_goalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_goalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_goalsActionPerformed

    private void add_assistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_assistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_assistsActionPerformed

    private void add_clean_sheetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_clean_sheetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_clean_sheetsActionPerformed

    private void add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_backActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin();
        a.show();
        this.dispose();
    }//GEN-LAST:event_add_backActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        try {
            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(400, 400, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            add_photo.setIcon(icon);
            path2 = path;
        } catch (IOException ex) {
            Logger.getLogger(AddNewPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uploadActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if (search_name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter name to search");
        } else {
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/players", "root", "1234");
                String sql = "SELECT * FROM playerdata WHERE name = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                String name = search_name.getText();                
                ps.setString(1, name);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    String name2 = rs.getString(2);
                    String country = rs.getString(3);
                    String club = rs.getString(4);
                    String position = rs.getString(5);
                    String played = rs.getString(6);
                    String goals = rs.getString(7);
                    String assists = rs.getString(8);
                    String clean_sheets = rs.getString(9);
                    
                    Blob image = rs.getBlob(14);
                    String path = "C:\\Users\\never\\OneDrive\\Documents\\NetBeansProjects\\nrproject\\src\\nrproject\\images\\img.jpg";
                    byte [] bytea = image.getBytes(1, (int)image.length());
                    FileOutputStream fos = new FileOutputStream(path);
                    fos.write(bytea);
                    ImageIcon icon = new ImageIcon(bytea);
                    add_photo.setIcon(icon);
                    
                    search_name.setText(name2);
                    add_country.setText(country);
                    add_club.setText(club);
                    add_position.setText(position);
                    add_played.setText(played);
                    add_goals.setText(goals);
                    add_assists.setText(assists);
                    add_clean_sheets.setText(clean_sheets);
                }
                else
                    JOptionPane.showMessageDialog(null, "Player Not Found");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePlayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_assists;
    private javax.swing.JButton add_back;
    private javax.swing.JTextField add_clean_sheets;
    private javax.swing.JTextField add_club;
    private javax.swing.JTextField add_country;
    private javax.swing.JTextField add_goals;
    private javax.swing.JLabel add_photo;
    private javax.swing.JTextField add_played;
    private javax.swing.JTextField add_position;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel min;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_name;
    private javax.swing.JButton update_player;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
