/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nrproject;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 */
public class User extends javax.swing.JFrame {
    int user;
    String p5;
    String p3;
    String p1;
    Connection c;
    Connection c2;
    String sql;
    String sqlU;
    PreparedStatement ptst;
    PreparedStatement ptstU;
    ResultSet rs;
    ResultSet rsU;
    /**
     * Creates new form User
     */
    public User() {
        setUndecorated(true);
        initComponents();
    }
    
    public User(int u) throws SQLException {
        setUndecorated(true);
        initComponents();
        user = u;
        
        c = DriverManager.getConnection("jdbc:mysql://localhost:3306/players", "root", "1234");
        c2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/userlogin", "root", "1234");
        sql = "select * from playerdata";
        sqlU = "select * from user_registration where idno='" + user + "'";
        ptst = c.prepareStatement(sql);
        ptstU = c2.prepareStatement(sqlU);
        rs = ptst.executeQuery();
        rsU = ptstU.executeQuery();
        if(rsU.next()){
            p5 = rsU.getString(6);
            p3 = rsU.getString(7);
            p1 = rsU.getString(8);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        user_5_points = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        user_3_points = new javax.swing.JButton();
        min = new javax.swing.JLabel();
        user_view_nominees = new javax.swing.JButton();
        user_1_points = new javax.swing.JButton();
        user_log_out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\never\\Downloads\\253366149b6be918e2ebde00adc5d818_400x480.jpg")); // NOI18N
        jLabel8.setAlignmentY(0.0F);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setIconTextGap(0);

        jPanel1.setBackground(new java.awt.Color(72, 219, 251));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(454, 480));

        user_5_points.setBackground(new java.awt.Color(0, 0, 0));
        user_5_points.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        user_5_points.setForeground(new java.awt.Color(255, 255, 255));
        user_5_points.setText("5 POINTS VOTE");
        user_5_points.setAlignmentY(0.0F);
        user_5_points.setBorderPainted(false);
        user_5_points.setFocusPainted(false);
        user_5_points.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_5_points.setMargin(new java.awt.Insets(2, 10, 2, 10));
        user_5_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_5_pointsActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\never\\Downloads\\output-onlinepngtools.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setText("USER INTERFACE");

        exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        user_3_points.setBackground(new java.awt.Color(0, 0, 0));
        user_3_points.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        user_3_points.setForeground(new java.awt.Color(255, 255, 255));
        user_3_points.setText("3 POINTS VOTE");
        user_3_points.setAlignmentY(0.0F);
        user_3_points.setBorderPainted(false);
        user_3_points.setFocusPainted(false);
        user_3_points.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_3_points.setMargin(new java.awt.Insets(2, 10, 2, 10));
        user_3_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_3_pointsActionPerformed(evt);
            }
        });

        min.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        min.setText("-");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        user_view_nominees.setBackground(new java.awt.Color(0, 0, 0));
        user_view_nominees.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        user_view_nominees.setForeground(new java.awt.Color(255, 255, 255));
        user_view_nominees.setText("VIEW NOMINEES");
        user_view_nominees.setAlignmentY(0.0F);
        user_view_nominees.setBorderPainted(false);
        user_view_nominees.setFocusPainted(false);
        user_view_nominees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_view_nominees.setMargin(new java.awt.Insets(2, 10, 2, 10));
        user_view_nominees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_view_nomineesActionPerformed(evt);
            }
        });

        user_1_points.setBackground(new java.awt.Color(0, 0, 0));
        user_1_points.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        user_1_points.setForeground(new java.awt.Color(255, 255, 255));
        user_1_points.setText("1 POINTS VOTE");
        user_1_points.setAlignmentY(0.0F);
        user_1_points.setBorderPainted(false);
        user_1_points.setFocusPainted(false);
        user_1_points.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_1_points.setMargin(new java.awt.Insets(2, 10, 2, 10));
        user_1_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_1_pointsActionPerformed(evt);
            }
        });

        user_log_out.setBackground(new java.awt.Color(0, 0, 0));
        user_log_out.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        user_log_out.setForeground(new java.awt.Color(255, 255, 255));
        user_log_out.setText("LOG OUT");
        user_log_out.setAlignmentY(0.0F);
        user_log_out.setBorderPainted(false);
        user_log_out.setFocusPainted(false);
        user_log_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_log_out.setMargin(new java.awt.Insets(2, 10, 2, 10));
        user_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_log_outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(user_5_points, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_3_points, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_1_points, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_view_nominees, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(user_log_out, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exit)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(min))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(user_5_points)
                .addGap(30, 30, 30)
                .addComponent(user_3_points)
                .addGap(30, 30, 30)
                .addComponent(user_1_points)
                .addGap(30, 30, 30)
                .addComponent(user_view_nominees)
                .addGap(30, 30, 30)
                .addComponent(user_log_out)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_5_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_5_pointsActionPerformed
        int mark = 0;
        try {
            rs = ptst.executeQuery();
            while(rs.next())
            {
                if(rs.getString(2).equals(p5))
                {
                    mark = 1;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(mark==1){
                JOptionPane.showMessageDialog(null, "Already Voted For "+p5);
            }
            else{
                VotePoints5 v = new VotePoints5(user);
                v.show();
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_user_5_pointsActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void user_3_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_3_pointsActionPerformed
        int mark = 0;
        try {
            rs = ptst.executeQuery();
            while(rs.next())
            {
                if(rs.getString(2).equals(p3))
                {
                    mark = 1;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            if(mark==1){
                JOptionPane.showMessageDialog(null, "Already Voted For "+p3);
            }
            else{
                VotePoints3 v = new VotePoints3(user);
                v.show();
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_user_3_pointsActionPerformed

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void user_view_nomineesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_view_nomineesActionPerformed
        try {
            // TODO add your handling code here:
            ViewPlayersUser v = new ViewPlayersUser(user);
            v.show();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_user_view_nomineesActionPerformed

    private void user_1_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_1_pointsActionPerformed
        int mark = 0;
        try {
            rs = ptst.executeQuery();
            while(rs.next())
            {
                if(rs.getString(2).equals(p1))
                {
                    mark = 1;
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            if(mark==1){
                JOptionPane.showMessageDialog(null, "Already Voted For "+p1);
            }
            else{
                VotePoints1 v = new VotePoints1(user);
                v.show();
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_user_1_pointsActionPerformed

    private void user_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_log_outActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        this.dispose();
    }//GEN-LAST:event_user_log_outActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel min;
    private javax.swing.JButton user_1_points;
    private javax.swing.JButton user_3_points;
    private javax.swing.JButton user_5_points;
    private javax.swing.JButton user_log_out;
    private javax.swing.JButton user_view_nominees;
    // End of variables declaration//GEN-END:variables
}
