/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nrproject;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author never
 */
public class ViewPlayersAdmin extends javax.swing.JFrame {
    String path2 = null;
    Connection c;
    String sql;
    PreparedStatement ptst;
    ResultSet rs;
    /**
     * Creates new form ViewPlayers
     */
    public ViewPlayersAdmin() throws SQLException, FileNotFoundException, IOException {
        setUndecorated(true);
        initComponents();
        c = DriverManager.getConnection("jdbc:mysql://localhost:3306/players", "root", "1234");
        sql = "select * from playerdata";
        ptst = c.prepareStatement(sql,ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        rs = ptst.executeQuery();
        
        if(rs.next()){
            String name2 = rs.getString(2);
            String country = rs.getString(3);
            String club = rs.getString(4);
            String position = rs.getString(5);
            String played = rs.getString(6);
            String goals = rs.getString(7);
            String assists = rs.getString(8);
            String clean_sheets = rs.getString(9);
            String total_points = rs.getString(10);
            String points5 = rs.getString(11);
            String points3 = rs.getString(12);
            String points1 = rs.getString(13);

            Blob image = rs.getBlob(14);
            String path = "C:\\Users\\never\\OneDrive\\Documents\\NetBeansProjects\\nrproject\\src\\nrproject\\images\\img.jpg";
            byte [] bytea = image.getBytes(1, (int)image.length());
            FileOutputStream fos = new FileOutputStream(path);
            fos.write(bytea);
            ImageIcon icon = new ImageIcon(bytea);
            add_photo.setIcon(icon);

            search_name.setText(name2);
            add_country.setText(country);
            add_club.setText(club);
            add_position.setText(position);
            add_played.setText(played);
            add_goals.setText(goals);
            add_assists.setText(assists);
            add_clean_sheets.setText(clean_sheets);
            add_total_points.setText(total_points);
            add_5_points.setText(points5);
            add_3_points.setText(points3);
            add_1_points.setText(points1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add_club = new javax.swing.JTextField();
        search_name = new javax.swing.JTextField();
        add_country = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        add_position = new javax.swing.JTextField();
        add_played = new javax.swing.JTextField();
        add_goals = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        add_assists = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        add_clean_sheets = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        add_total_points = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        add_5_points = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        add_3_points = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        add_1_points = new javax.swing.JTextField();
        add_photo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        add_back = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 219, 251));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(454, 480));

        add_club.setEditable(false);
        add_club.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_club.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_clubActionPerformed(evt);
            }
        });

        search_name.setEditable(false);
        search_name.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        search_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_nameActionPerformed(evt);
            }
        });

        add_country.setEditable(false);
        add_country.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_country.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                add_countryComponentShown(evt);
            }
        });
        add_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_countryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel2.setText("Full Name :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel4.setText("Country :");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel6.setText("Club :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel7.setText("Position :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel8.setText("Games Played :");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        min.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        min.setText("-");
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        add_position.setEditable(false);
        add_position.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_positionActionPerformed(evt);
            }
        });

        add_played.setEditable(false);
        add_played.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_played.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_playedActionPerformed(evt);
            }
        });

        add_goals.setEditable(false);
        add_goals.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_goalsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel9.setText("Goals :");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_assists.setEditable(false);
        add_assists.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_assists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_assistsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel10.setText("Assists :");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_clean_sheets.setEditable(false);
        add_clean_sheets.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_clean_sheets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_clean_sheetsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel11.setText("Clean Sheets :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setText("PLAYER DETAILS");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel12.setText("Total Points :");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_total_points.setEditable(false);
        add_total_points.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_total_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_total_pointsActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel13.setText("No. of 5 Points :");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_5_points.setEditable(false);
        add_5_points.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_5_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_5_pointsActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel14.setText("No. of 3 Points :");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_3_points.setEditable(false);
        add_3_points.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_3_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_3_pointsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel15.setText("No. of 1 Points :");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        add_1_points.setEditable(false);
        add_1_points.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        add_1_points.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_1_pointsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(122, 122, 122))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(min)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exit))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(add_1_points, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_3_points, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_5_points, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add_total_points, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(add_clean_sheets, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_assists, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_played, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_position, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_club, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add_country, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exit)
                        .addComponent(min))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_country, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_club, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_position, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_played, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_assists, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_clean_sheets, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_total_points, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_5_points, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_3_points, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_1_points, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add_photo.setAlignmentY(0.0F);
        add_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 2));
        add_photo.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel2.setBackground(new java.awt.Color(72, 219, 251));
        jPanel2.setPreferredSize(new java.awt.Dimension(401, 80));

        add_back.setBackground(new java.awt.Color(0, 0, 0));
        add_back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        add_back.setForeground(new java.awt.Color(255, 255, 255));
        add_back.setText("BACK TO ADMIN PANEL");
        add_back.setAlignmentY(0.0F);
        add_back.setBorderPainted(false);
        add_back.setFocusPainted(false);
        add_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add_back.setIconTextGap(0);
        add_back.setMargin(new java.awt.Insets(2, 10, 2, 10));
        add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_backActionPerformed(evt);
            }
        });

        previous.setBackground(new java.awt.Color(0, 0, 0));
        previous.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        previous.setForeground(new java.awt.Color(255, 255, 255));
        previous.setText("<");
        previous.setAlignmentY(0.0F);
        previous.setBorderPainted(false);
        previous.setFocusPainted(false);
        previous.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previous.setMargin(new java.awt.Insets(2, 10, 2, 10));
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(0, 0, 0));
        next.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText(">");
        next.setAlignmentY(0.0F);
        next.setBorderPainted(false);
        next.setFocusPainted(false);
        next.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        next.setMargin(new java.awt.Insets(2, 10, 2, 10));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(add_back, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(add_back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(add_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(add_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_clubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_clubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_clubActionPerformed

    private void search_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_nameActionPerformed

    private void add_countryComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_add_countryComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_add_countryComponentShown

    private void add_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_countryActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try {
            // TODO add your handling code here:
            if(rs.next()){
                String name2 = rs.getString(2);
                String country = rs.getString(3);
                String club = rs.getString(4);
                String position = rs.getString(5);
                String played = rs.getString(6);
                String goals = rs.getString(7);
                String assists = rs.getString(8);
                String clean_sheets = rs.getString(9);
                String total_points = rs.getString(10);
                String points5 = rs.getString(11);
                String points3 = rs.getString(12);
                String points1 = rs.getString(13);
                
                Blob image = rs.getBlob(14);
                String path = "C:\\Users\\never\\OneDrive\\Documents\\NetBeansProjects\\nrproject\\src\\nrproject\\images\\img.jpg";
                byte [] bytea = image.getBytes(1, (int)image.length());
                FileOutputStream fos = new FileOutputStream(path);
                fos.write(bytea);
                ImageIcon icon = new ImageIcon(bytea);
                add_photo.setIcon(icon);
                
                search_name.setText(name2);
                add_country.setText(country);
                add_club.setText(club);
                add_position.setText(position);
                add_played.setText(played);
                add_goals.setText(goals);
                add_assists.setText(assists);
                add_clean_sheets.setText(clean_sheets);
                add_total_points.setText(total_points);
                add_5_points.setText(points5);
                add_3_points.setText(points3);
                add_1_points.setText(points1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void add_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_positionActionPerformed

    private void add_playedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_playedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_playedActionPerformed

    private void add_goalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_goalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_goalsActionPerformed

    private void add_assistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_assistsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_assistsActionPerformed

    private void add_clean_sheetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_clean_sheetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_clean_sheetsActionPerformed

    private void add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_backActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin();
        a.show();
        this.dispose();
    }//GEN-LAST:event_add_backActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        try {
            if(rs.previous()){
                String name2 = rs.getString(2);
                String country = rs.getString(3);
                String club = rs.getString(4);
                String position = rs.getString(5);
                String played = rs.getString(6);
                String goals = rs.getString(7);
                String assists = rs.getString(8);
                String clean_sheets = rs.getString(9);
                String total_points = rs.getString(10);
                String points5 = rs.getString(11);
                String points3 = rs.getString(12);
                String points1 = rs.getString(13);
                
                Blob image = rs.getBlob(14);
                String path = "C:\\Users\\never\\OneDrive\\Documents\\NetBeansProjects\\nrproject\\src\\nrproject\\images\\img.jpg";
                byte [] bytea = image.getBytes(1, (int)image.length());
                FileOutputStream fos = new FileOutputStream(path);
                fos.write(bytea);
                ImageIcon icon = new ImageIcon(bytea);
                add_photo.setIcon(icon);
                
                search_name.setText(name2);
                add_country.setText(country);
                add_club.setText(club);
                add_position.setText(position);
                add_played.setText(played);
                add_goals.setText(goals);
                add_assists.setText(assists);
                add_clean_sheets.setText(clean_sheets);
                add_total_points.setText(total_points);
                add_5_points.setText(points5);
                add_3_points.setText(points3);
                add_1_points.setText(points1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_previousActionPerformed

    private void add_total_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_total_pointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_total_pointsActionPerformed

    private void add_5_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_5_pointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_5_pointsActionPerformed

    private void add_3_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_3_pointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_3_pointsActionPerformed

    private void add_1_pointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_1_pointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_1_pointsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPlayersAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPlayersAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPlayersAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPlayersAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewPlayersAdmin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ViewPlayersAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_1_points;
    private javax.swing.JTextField add_3_points;
    private javax.swing.JTextField add_5_points;
    private javax.swing.JTextField add_assists;
    private javax.swing.JButton add_back;
    private javax.swing.JTextField add_clean_sheets;
    private javax.swing.JTextField add_club;
    private javax.swing.JTextField add_country;
    private javax.swing.JTextField add_goals;
    private javax.swing.JLabel add_photo;
    private javax.swing.JTextField add_played;
    private javax.swing.JTextField add_position;
    private javax.swing.JTextField add_total_points;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel min;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    private javax.swing.JTextField search_name;
    // End of variables declaration//GEN-END:variables
}
